# -*- coding: utf-8 -*-
#
#  TECS Generator
#      Generator for TOPPERS Embedded Component System
#  
#   Copyright (C) 2024-2026 by TOPPERS Project
#--
#   上記著作権者は，以下の(1)〜(4)の条件を満たす場合に限り，本ソフトウェ
#   ア（本ソフトウェアを改変したものを含む．以下同じ）を使用・複製・改
#   変・再配布（以下，利用と呼ぶ）することを無償で許諾する．
#   (1) 本ソフトウェアをソースコードの形で利用する場合には，上記の著作
#       権表示，この利用条件および下記の無保証規定が，そのままの形でソー
#       スコード中に含まれていること．
#   (2) 本ソフトウェアを，ライブラリ形式など，他のソフトウェア開発に使
#       用できる形で再配布する場合には，再配布に伴うドキュメント（利用
#       者マニュアルなど）に，上記の著作権表示，この利用条件および下記
#       の無保証規定を掲載すること．
#   (3) 本ソフトウェアを，機器に組み込むなど，他のソフトウェア開発に使
#       用できない形で再配布する場合には，次のいずれかの条件を満たすこ
#       と．
#     (a) 再配布に伴うドキュメント（利用者マニュアルなど）に，上記の著
#         作権表示，この利用条件および下記の無保証規定を掲載すること．
#     (b) 再配布の形態を，別に定める方法によって，TOPPERSプロジェクトに
#         報告すること．
#   (4) 本ソフトウェアの利用により直接的または間接的に生じるいかなる損
#       害からも，上記著作権者およびTOPPERSプロジェクトを免責すること．
#       また，本ソフトウェアのユーザまたはエンドユーザからのいかなる理
#       由に基づく請求からも，上記著作権者およびTOPPERSプロジェクトを
#       免責すること．
#  
#   本ソフトウェアは，無保証で提供されているものである．上記著作権者お
#   よびTOPPERSプロジェクトは，本ソフトウェアに関して，特定の使用目的
#   に対する適合性も含めて，いかなる保証も行わない．また，本ソフトウェ
#   アの利用により直接的または間接的に生じたいかなる損害に関しても，そ
#   の責任を負わない．
#  
#   $Id: DataPumpHolderPlugin.rb 3300 2026-01-04 12:29:45Z okuma-top $
#++



=begin
DataPumpHolderPlugin
データポンプ＆ホルダ生成プラグイン (セルタイププラグイン)

データポンプ＆ホルダ生成プラグインは、セルタイプに適用するプラグインで、
以下のものを生成する。
  セルタイプ： データポンプセルタイプ、データホルダセルタイプ
  シグニチャ： プットシグニチャ(Put)、ゲットシグニチャ(Get)

このプラグインが適用されたセルタイプの属性、変数で定義したデータを授受するための
セルタイプ2種類と、セルタイプの呼び口、または受け口のためのシグニチャ2種類を生成する。

プットシグニチャは、データを生成する側からデータを消費する側にデータを送出する際に使用する。
ゲットシグニチャは、データを消費する側がデータを生成する側からデータを受取る際に使用する。

データポンプセルタイプは、データを生成する側からデータを受取り、
データを消費する側にデータを送出する。
データポンプセルタイプの持つ2つの呼び口から行われる。

データホルダセルタイプは、データを生成する側からデータが送出され、
データを消費する側がデータを受取る。
データホルダセルタイプの持つ2つの受け口から行われる。

                  |  データ生成側               データ消費側
                  | 口タイプ　(シグニチャ)      口タイプ (シグニチャ)
------------------+----------------------------------------
データポンプセル    | 呼び口 (Get)              呼び口 (Put)
データホルダセル    | 受け口 (Put)              受け口 (Get)

プラグインを適用するセルタイプの属性は読出し専用データ、変数は読書き可能データとみなされる。
読書き可能なデータのみを設定可能とする、セットシグニチャも用意される。

データ授受構造分類と、それぞれのデータ授受構造(最小構成)をまとめると下表のようになる。

分類    データ生成側    データ消費側      データ授受構造(最小構成)
---------------------------------------------------------------------
CⅠ型    受け口 (Put)    呼び口 (Put)     直接結合
CⅡ型    呼び口  (Get)   受型口 (Get)     データポンプ＋データホルダ
CⅢ型    受け口  (Put)   受け口 (Get)     データホルダ
CⅣ型    呼び口  (Get)   呼び口 (Put)     データポンプ



[generate(DataPumpHolderPlugin,"")]
celltype tSomeData {
  attr{        // read only data
     int    sensor_data;
  };
  var {        // writable data
     int    actuator_stat;
  };
};

=end

#== celltype プラグインの共通の親クラス
class DataPumpHolderPlugin < CelltypePlugin

  @@count = 0      # 何回、このプラグインが呼ばれたか

  #celltype::     Celltype        セルタイプ（インスタンス）
  def initialize( celltype, option )
    super
    @celltype = celltype
    # @plugin_arg_str = option.gsub( /\A"(.*)/, '\1' )    # 前後の "" を取り除く
    # @plugin_arg_str.sub!( /(.*)"\z/, '\1' )
    @plugin_arg_str = CDLString.remove_dquote option
    @plugin_arg_list = {}
    @cell_list =[]

    # 
    @namespace_pre = @celltype.get_namespace.get_global_name
    @signature_pre = @celltype.get_name.to_s.sub( /^t/, "s" )
    @signature_prefix = @namespace_pre + "_" + @signature_pre
    @celltype_prefix  = @celltype.get_global_name
    @celltype_cdl_name = @celltype.get_global_name.to_s + "_celltype.cdl"
    @signature_cdl_name = @celltype.get_global_name.to_s + "_signature.cdl"

    # @attr_list, @var_list および、その中身は参照するだけ
    @attr_list = @celltype.get_attribute_list
    @var_list  = @celltype.get_var_list

    signame = @celltype.get_name.to_s.sub( /^t/, "s")
    @get_signature = "#{signame}GetSignature"
    @set_signature = "#{signame}SetSignature"
    @datapump_celltype = "#{@celltype.get_name}DataPump"
    @dataholder_celltype = "#{@celltype.get_name}DataHolder"
    @datapumpholder_celltype = "#{@celltype.get_name}DataPumpHolder"
    @set_signature_async     = "#{signame}SetSignatureAsync"
    @sync_adaptor_celltype   = "#{@celltype.get_name}SyncAdaptor";
    @async_adaptor_celltype  = "#{@celltype.get_name}AsyncAdaptor";
    gen_get_set_signature
    gen_pump_holder_celltype
  end

  #=== 新しいセル
  #cell::        Cell            セル
  #
  # celltype プラグインを指定されたセルタイプのセルが生成された
  # セルタイププラグインに対する新しいセルの報告
  def new_cell( cell )
      @cell_list << cell
  end
  
  #=== 後ろの CDL コードを生成
  #プラグインの後ろの CDL コードを生成
  #file:: File: 
  def self.gen_post_code( file )
    # 複数のプラグインの post_code が一つのファイルに含まれるため、以下のような見出しをつけること
    # file.print "/* '#{self.class.name}' post code */\n"
  end

  #=== tCelltype_factory.h に挿入するコードを生成する
  # file 以外の他のファイルにファクトリコードを生成してもよい
  # セルタイププラグインが指定されたセルタイプのみ呼び出される
  def gen_factory file
  end

  def gen_cdl_file file
    file.print <<EOT
/*
* This file is generated by DataPumpHolderPlugin from #{@celltype.get_namespace_path}
*/

// import DataPumpHolder.cdl which imports rpc.cdl and kernel.cdl
import( <DataPumpHolder.cdl> );

// signature definition for data set & get in #{@celltype.get_namespace_path}
EOT
    file.print "import( \"#{@signature_cdl_name}\" );\n"
    file.print "import( \"#{@celltype_cdl_name}\" );\n"
  end

  def gen_get_set_signature
    print <<EOT
[DataPumpHolderPlugin] for DATA #{@celltype.get_name}
      signatures in      #{$gen}/#{@signature_cdl_name}
                for  GET #{@get_signature}
                for  SET #{@set_signature}
      celltypes  in      #{$gen}/#{@celltype_cdl_name}
                for PUMP #{@datapump_celltype}
              for HOLDER #{@dataholder_celltype}
          for PUMPHOLDER #{@datapumpholder_celltype}
EOT
    file = CFile.open( "#{$gen}/#{@celltype.get_global_name}_signature.cdl", "w" )
    file.print <<EOT
/*
* This file is generated by DataPumpHolderPlugin from #{@celltype.get_namespace_path}
*/

// Get signature for #{@celltype.get_namespace_path}
//   Get signature is used for
//      DataPump        cPubSide
//      DataHolder      eSubSide
//      DataPumpHolder  cPubSide, eSubSide
signature #{@get_signature}{
    // Sync Control functions
    ER  waitForNewData(void);    // This function may block.
    ER  dataReadDone(void);

    // Data Access functions
EOT
    (@attr_list+@var_list).each{ |decl|
      if decl.get_ptr_level == 0 then ptr = "*" else ptr = "" end
      if( decl.get_size_is ) then
        spec = "[out, size_is(#{decl.get_size_is})]"
      else
        spec = "[out]"
      end
      file.print <<EOT
    ER get_#{decl.get_identifier}( #{spec}#{decl.get_type.get_type_str}\t#{ptr}#{decl.get_identifier}#{decl.get_type.get_type_str_post} );
EOT
    }
    file.print <<EOT
};
EOT
    file.print <<EOT

// Set signature for #{@celltype.get_namespace_path}
//   Set signature is used for
//      DataPump        cSubSide
//      DataHolder      ePubSide
signature #{@set_signature}{
    // Sync Control functions
    ER  waitForReadDone(void);    // This function may block.
    [oneway]
      ER  newDataReady(void);

    // Data Set functions
EOT
    (@attr_list+@var_list).each{ |decl|
      if decl.get_ptr_level == 0 then ptr = "*" else ptr = "" end
      if( decl.get_size_is ) then
        spec = "[in, size_is(#{decl.get_size_is})]"
      else
        spec = "[in]"
      end
      file.print <<EOT
    [oneway]
      ER set_#{decl.get_identifier}( #{spec}const #{decl.get_type.get_type_str}\t#{decl.get_identifier}#{decl.get_type.get_type_str_post} );
EOT
    }
    file.print <<EOT
};
EOT
    file.print <<EOT

// Set signature for #{@celltype.get_namespace_path}
//   This Set signature is used for buffer asynchronous buffer communication.
//   waitForReadDone is to notify new data arraival and
//         executed asynchronously in client side and synchronously in server side.
signature #{@set_signature_async}{
    // Sync Control functions (async for RPC buffer)
    [oneway]
      ER  waitForReadDone(void);    // This function may block.
    [oneway]
      ER  newDataReady(void);

    // Data Set functions
EOT
    (@attr_list+@var_list).each{ |decl|
      if decl.get_ptr_level == 0 then ptr = "*" else ptr = "" end
      if( decl.get_size_is ) then
        spec = "[in, size_is(#{decl.get_size_is})]"
      else
        spec = "[in]"
      end
      file.print <<EOT
    [oneway]
      ER set_#{decl.get_identifier}( #{spec}const #{decl.get_type.get_type_str}\t#{decl.get_identifier}#{decl.get_type.get_type_str_post} );
EOT
    }
    file.print <<EOT
};
EOT
    file.close
  end

  def gen_pump_holder_celltype
    file = CFile.open( "#{$gen}/#{@celltype.get_global_name}_celltype.cdl", "w" )
    file.print <<EOT
/*
 * generated by DataPumpHolderPlugin
 * for celltype #{@celltype.get_namespace_path}
 * This includes celltypes #{@datapump_celltype}, #{@datholder_celltype} & #{@datapumpholder_celltype}
 */
 
//---------  Data Pump Celltype ---------
celltype #{@datapump_celltype} {
  entry sPumpMain ePumpMain;
  call #{@get_signature} cPubSide;
  call #{@set_signature} cSubSide;
};

//---------  Data Holder Celltype ---------
celltype #{@dataholder_celltype} {
  entry #{@get_signature} eSubSide;
  entry #{@set_signature} ePubSide;
  [optional]
     call sEventflag    cEventflag;
  var {
EOT

    (@attr_list+@var_list).each{ |decl|
        if( decl.get_size_is ) then
          spec = "[size_is(#{decl.get_size_is})]\n        "
        else
          spec = ""
        end

        file.print "     #{spec}#{decl.get_type.get_type_str}\t#{decl.get_name}#{decl.get_type.get_type_str_post};\n"
    }
    file.print <<EOT
    int_t  status;
  };
};

//---------  Data Holder Celltype ---------
celltype #{@sync_adaptor_celltype} {
  [inline]
    entry #{@set_signature}     eIn;
  call  #{@set_signature_async} cOut;
};

celltype #{@async_adaptor_celltype} {
  [inline]
    entry #{@set_signature_async} eIn;
  call  #{@set_signature}         cOut;
};

//---  Data Pump & Holder Celltype (composite) ---
composite #{@datapumpholder_celltype} {
  call  #{@get_signature} cPubSide;
  entry #{@get_signature} eSubSide;
  entry sPumpMain ePumpMain;

  cell #{@dataholder_celltype} Holder {
  };
  cell #{@datapump_celltype}   Pump {
    cSubSide =  Holder.ePubSide;
    cPubSide => composite.cPubSide;
  };
  composite.eSubSide => Holder.eSubSide;
  composite.ePumpMain => Pump.ePumpMain;
};

//---------  Data Holder Celltype Sync (composite) ---------
composite #{@dataholder_celltype}Sync {
  entry #{@set_signature} ePubSide;
  entry #{@get_signature} eSubSide;

  cell #{@dataholder_celltype} Holder {
    cEventflag = Eventflag.eEventflag;
  };
  cell tEventflag Eventflag{
    flagPattern = DATAHOLDER_EVFLAG_READ_DONE;  // Data Read Done status at beginning
  };
  composite.eSubSide => Holder.eSubSide;
  composite.ePubSide => Holder.ePubSide;
};

//---------  Data Pump & Holder Celltype  Sync (composite) ---------
composite #{@datapumpholder_celltype}Sync {
  call  #{@get_signature} cPubSide;
  entry #{@get_signature} eSubSide;
  entry sPumpMain ePumpMain;

  cell #{@dataholder_celltype} Holder {
    cEventflag = Eventflag.eEventflag;
  };
  cell #{@datapump_celltype}   Pump {
    cSubSide =  Holder.ePubSide;
    cPubSide => composite.cPubSide;
  };
  cell tEventflag Eventflag{
    flagPattern = 0;
  };
  composite.eSubSide => Holder.eSubSide;
  composite.ePumpMain => Pump.ePumpMain;
};

//---------  Trasnparent RPC Marshaler Channel celltypes  --------
generate(TransparentRPCSignaturePlugin, #{@set_signature_async}, "PPAllocatorSize=128,DataPumpHolder=true");

//---------  DataPumpBuffered ----------
[active]
composite #{@datapump_celltype}Buffered {
  attr {
    PRI     taskPriority;
    size_t  stackSize = 4096;
    ATR     attribute = C_EXP( "TA_ACT" );  // marshaler starts at the beginning
  };
  call #{@set_signature} cSubSide;
  call #{@get_signature} cPubSide;
  entry sPumpMain ePumpMain;

  cell #{@datapump_celltype} DataPump {
    cSubSide = SyncAdaptor.eIn;
    cPubSide => composite.cPubSide;
  };
  cell #{@sync_adaptor_celltype} SyncAdaptor{
    cOut = SetRPCChannel.eThroughEntry;
  };
  cell tRPCPluginDPH_tTDR_tDataqueueOWChannel_#{@set_signature_async}  SetRPCChannel{
    cCall = AsyncAdaptor.eIn;
    taskPriority  = composite.taskPriority;
    attribute = composite.attribute;
    stackSize = composite.stackSize;
  };
  cell #{@async_adaptor_celltype} AsyncAdaptor{
    cOut => composite.cSubSide;
  };
  cell tPumpMainConverter PumpMain {
    cMain = DataPump.ePumpMain;
  };
  cell tTask Task {
    cTaskBody = PumpMain.eTaskBody;
    priority  = composite.taskPriority;
    attribute = composite.attribute;
    stackSize = composite.stackSize;
  };
  composite.ePumpMain => DataPump.ePumpMain;
};

//---------  DataHolderBuffered ----------
[active]
composite #{@dataholder_celltype}Buffered {
  attr {
    PRI     taskPriority;
    size_t  stackSize = 4096;
    ATR     attribute = C_EXP( "TA_ACT" );  // marshaler starts at the beginning
  };
  entry #{@set_signature} ePubSide;
  entry #{@get_signature} eSubSide;

  cell #{@sync_adaptor_celltype} SyncAdaptor{
    cOut = SetRPCChannel.eThroughEntry;
  };
  cell tRPCPluginDPH_tTDR_tDataqueueOWChannel_#{@set_signature_async}  SetRPCChannel{
    cCall = AsyncAdaptor.eIn;
    taskPriority  = composite.taskPriority;
    attribute = composite.attribute;
    stackSize = composite.stackSize;
  };
  cell #{@async_adaptor_celltype} AsyncAdaptor{
    cOut = DataHolder.ePubSide;
  };
  cell #{@dataholder_celltype} DataHolder {
  };
  composite.ePubSide => SyncAdaptor.eIn;
  composite.eSubSide => DataHolder.eSubSide;
};

//---------  DataPumpHolderBuffered ----------
[active]
composite #{@datapumpholder_celltype}Buffered {
  attr {
    PRI     taskPriority;
    size_t  stackSize = 4096;
    ATR     attribute = C_EXP( "TA_ACT" );  // marshaler starts at the beginning
  };
  entry #{@get_signature} eSubSide;
  call  #{@get_signature} cPubSide;
  entry sPumpMain ePumpMain;
  cell #{@dataholder_celltype} DataHolder {
  };
  cell #{@sync_adaptor_celltype} SyncAdaptor{
    cOut = SetRPCChannel.eThroughEntry;
  };
  cell tRPCPluginDPH_tTDR_tDataqueueOWChannel_#{@set_signature_async}  SetRPCChannel{
    cCall    = AsyncAdaptor.eIn;
    taskPriority  = composite.taskPriority;
    attribute = composite.attribute;
    stackSize = composite.stackSize;
  };
  cell #{@async_adaptor_celltype} AsyncAdaptor{
    cOut = DataHolder.ePubSide;
  };
  cell #{@datapump_celltype} DataPump {
    cSubSide = SyncAdaptor.eIn;
    cPubSide => composite.cPubSide;
  };
  cell tPumpMainConverter PumpMain {
    cMain = DataPump.ePumpMain;
  };
  cell tTask Task {
    cTaskBody = PumpMain.eTaskBody;
    priority  = composite.taskPriority;
    attribute = composite.attribute;
    stackSize = composite.stackSize;
  };
  composite.ePumpMain => DataPump.ePumpMain;
  composite.eSubSide  => DataHolder.eSubSide;
};

//---------  DataHolderBufferedSync ----------
[active]
composite #{@dataholder_celltype}BufferedSync {
  attr {
    PRI     taskPriority;
    size_t  stackSize = 4096;
    ATR     attribute = C_EXP( "TA_ACT" );  // marshaler starts at the beginning
  };
  entry #{@set_signature} ePubSide;
  entry #{@get_signature} eSubSide;

  cell #{@sync_adaptor_celltype} SyncAdaptor{
    cOut = SetRPCChannel.eThroughEntry;
  };
  cell tRPCPluginDPH_tTDR_tDataqueueOWChannel_#{@set_signature_async}  SetRPCChannel{
    cCall = AsyncAdaptor.eIn;
    taskPriority  = composite.taskPriority;
    attribute = composite.attribute;
    stackSize = composite.stackSize;
  };
  cell #{@async_adaptor_celltype} AsyncAdaptor{
    cOut = DataHolder.ePubSide;
  };
  cell #{@dataholder_celltype} DataHolder {
      cEventflag = Eventflag.eEventflag;
  };
  cell tEventflag Eventflag{
    flagPattern = 0;
  };
  composite.ePubSide => SyncAdaptor.eIn;
  composite.eSubSide => DataHolder.eSubSide;
};

//---------  DataPumpHolderBufferedSync ----------
[active]
composite #{@datapumpholder_celltype}BufferedSync {
  attr {
    PRI     taskPriority;
    size_t  stackSize = 4096;
    ATR     attribute = C_EXP( "TA_ACT" );  // marshaler starts at the beginning
  };
  entry #{@get_signature} eSubSide;
  call  #{@get_signature} cPubSide;
  entry sPumpMain ePumpMain;

  cell #{@dataholder_celltype} DataHolder {
    cEventflag = Eventflag.eEventflag;
  };
  cell tEventflag Eventflag{
    flagPattern = 0;
  };
  cell #{@sync_adaptor_celltype} SyncAdaptor{
    cOut = SetRPCChannel.eThroughEntry;
  };
  cell tRPCPluginDPH_tTDR_tDataqueueOWChannel_#{@set_signature_async}  SetRPCChannel{
    cCall    = AsyncAdaptor.eIn;
    taskPriority  = composite.taskPriority;
    attribute = composite.attribute;
    stackSize = composite.stackSize;
  };
  cell #{@async_adaptor_celltype} AsyncAdaptor{
    cOut = DataHolder.ePubSide;
  };
  cell #{@datapump_celltype} DataPump {
    cSubSide = SyncAdaptor.eIn;
    cPubSide => composite.cPubSide;
  };
  cell tPumpMainConverter PumpMain {
    cMain = DataPump.ePumpMain;
  };
  cell tTask Task {
    cTaskBody = PumpMain.eTaskBody;
    priority  = composite.taskPriority;
    attribute = composite.attribute;
    stackSize = composite.stackSize;
  };
  composite.ePumpMain => DataPump.ePumpMain;
  composite.eSubSide  => DataHolder.eSubSide;
};

EOT
    file.close
  end

  #== 受け口関数の中身を生成する
  def gen_ep_func_body( file, b_singleton, ct_name, global_ct_name, sig_name, ep_name, func_name, func_global_name, func_type, params )
    if ct_name == @datapump_celltype.to_sym then  ### DataPump Celltype ###
      #### DataPump セルタイプ ####
      file.print <<EOT
    ER      ercd = E_OK;                      // DataPumpHolderPlugin 0
    CELLCB  *p_cellcb = GET_CELLCB(idx);
    //  variables from data definition in celltype #{@celltype.get_name}
#ifdef DATAPUMPHOLDER_DEBUG
    syslog( LOG_INFO, "DataPumpHolderPlugin #{ct_name}.#{ep_name}.#{func_name}" );
#endif
EOT

      (@attr_list+@var_list).each{ |decl|
        if decl.get_ptr_level == 0 then ptr = "*" else ptr = "" end
        type = decl.get_type.get_original_type
        if type.kind_of? PtrType  then
          type = type.get_type    # ポインタの参照している型
        end
        if decl.get_size_is then
          size = "[#{decl.get_size_is}]"
          size_note = "    // note: if size of array is too large, stack overflow might happen here or later"
        else
          size = ""
          size_note = ""
        end
        file.print <<EOT
    #{type.get_type_str}\t#{decl.get_identifier}#{type.get_type_str_post}#{size};#{size_note}
EOT
      }

      file.print <<EOT

    // mikan: need error check
    cPubSide_waitForNewData();    // wait for PubSide
    cSubSide_waitForReadDone();   // wait for SubSuide
EOT
      (@attr_list+@var_list).each{ |decl|
        if decl.get_ptr_level == 0 then ref = "&" else ptr = "" end
        file.print <<EOT

    // data: #{decl.get_identifier} get & set
    cPubSide_get_#{decl.get_identifier}( #{ref}#{decl.get_identifier} );
    cSubSide_set_#{decl.get_identifier}( #{decl.get_identifier} );
EOT
      }
      file.print <<EOT

    /// mikan: need error check
    cPubSide_dataReadDone();
    cSubSide_newDataReady();

    return ercd;
EOT
    elsif ct_name == @dataholder_celltype.to_sym then   ### DataHolder Celltype ###
      #### DataHolder セルタイプ ####
      if ep_name == :"eSubSide" then            ### SubSide ###
        ### eSubSide 受け口 ####
        if func_name == :waitForNewData then    ##  waitForNewData ##
          file.print <<EOT
    // wait For PubSide New Data
    CELLCB   *p_cellcb = GET_CELLCB(idx);
    ER       ercd = E_OK;
    FLGPTN   flgptn;

#ifdef DATAPUMPHOLDER_DEBUG
    syslog( LOG_INFO, "DataPumpHolderPlugin #{ct_name}.#{ep_name}.#{func_name}" );
#endif
    if( is_cEventflag_joined() ){
      if( VAR_status != DATAHOLDER_STAT_READING ){
        ercd = cEventflag_wait( DATAHOLDER_EVFLAG_NEW_DATA, TWF_ANDW, &flgptn );
        (void)flgptn;
        if( ercd == E_OK ){
          VAR_status = DATAHOLDER_STAT_READING;
        }
      } else{
       ercd = E_PAR;
      }
    }
    return ercd;
EOT
        elsif func_name == :dataReadDone then    ##  dataReadDone ##
          file.print <<EOT
    // data Read Done
    CELLCB   *p_cellcb = GET_CELLCB(idx);
    ER       ercd = E_OK;

#ifdef DATAPUMPHOLDER_DEBUG
    syslog( LOG_INFO, "DataPumpHolderPlugin #{ct_name}.#{ep_name}.#{func_name}" );
#endif
    if( is_cEventflag_joined() ){
      if( VAR_status == DATAHOLDER_STAT_READING ){
        VAR_status = DATAHOLDER_STAT_READ_DONE;  // フラグを操作する前に変更
        ercd = cEventflag_clear( ~DATAHOLDER_EVFLAG_NEW_DATA );
        ercd = cEventflag_set( DATAHOLDER_EVFLAG_READ_DONE ); // ここで PubSide 動作開始可能
      } else {
        ercd = E_PAR;
      }
    }
    return ercd;
EOT
        else
          # データ
          file.print "/* #{ep_name}.#{func_name} */\n"
          dat_name = func_name.to_s.sub( /get_/, "" ).to_sym
          file.print "/* #{ep_name}.#{func_name} var_name: #{dat_name}*/\n"

          decla = find_decl dat_name
          if decla.get_ptr_level == 0 then
            file.print <<EOT
    CELLCB   *p_cellcb = GET_CELLCB(idx);
    *#{dat_name} = VAR_#{dat_name};
    return E_OK;
EOT
          elsif decla.get_ptr_level == 1 then
            if( decla.get_size_is ) then
              spec = "*#{decla.get_size_is}"
            else
              spec = ""
            end
            file.print <<EOT
    CELLCB   *p_cellcb = GET_CELLCB(idx);
    memcpy( #{dat_name}, VAR_#{dat_name}, sizeof(*#{dat_name})#{spec} );
    return E_OK;
EOT
          end
        end
      elsif ep_name == :"ePubSide" then          ### PubSide ###
        ### DataHolder ePubSide 受け口 ####
        if func_name == :waitForReadDone then    ##  waitForReadDone ##
          file.print <<EOT
    // Wait For SubSide Read-Done
    CELLCB   *p_cellcb = GET_CELLCB(idx);
    ER       ercd = E_OK;
    FLGPTN   flgptn;

#ifdef DATAPUMPHOLDER_DEBUG
    syslog( LOG_INFO, "DataPumpHolderPlugin #{ct_name}.#{ep_name}.#{func_name}" );
#endif
    if( is_cEventflag_joined() ){
      // cygwin_kernel.cdl の環境では、Eventflag の初期値が設定されないため
      // ここで設定する (この設定は、正規の環境で残っても問題ない)
      if( VAR_status == DATAHOLDER_STAT_NONE ){
        VAR_status= DATAHOLDER_STAT_READ_DONE;
        cEventflag_set( DATAHOLDER_EVFLAG_READ_DONE );
      }
      if( VAR_status != DATAHOLDER_STAT_WRITING ){
        ercd = cEventflag_wait( DATAHOLDER_EVFLAG_READ_DONE, TWF_ANDW, &flgptn );
        (void)flgptn;
        if( ercd == E_OK ){
          VAR_status = DATAHOLDER_STAT_WRITING;
        }
      } else{
        ercd = E_PAR;
      }
    }
    return ercd;
EOT
        elsif func_name == :newDataReady then    ##  newDataReady ##
          file.print <<EOT
    // New Data Ready
    CELLCB   *p_cellcb = GET_CELLCB(idx);
    ER       ercd = E_OK;

#ifdef DATAPUMPHOLDER_DEBUG
    syslog( LOG_INFO, "DataPumpHolderPlugin #{ct_name}.#{ep_name}.#{func_name}" );
#endif
    if( is_cEventflag_joined() ){
      if( VAR_status == DATAHOLDER_STAT_WRITING ){
        VAR_status = DATAHOLDER_STAT_WRITE_DONE;  // フラグを操作する前に変更
        ercd = cEventflag_clear( ~DATAHOLDER_EVFLAG_READ_DONE );
        ercd = cEventflag_set( DATAHOLDER_EVFLAG_NEW_DATA ); // ここで SubSide 動作開始可能
      } else{
       ercd = E_PAR;
      }
    }
    return ercd;
EOT
        else
          # データ
          dat_name = func_name.to_s.sub( /set_/, "" ).to_sym
          file.print "/* #{ep_name}.#{func_name} var_name: #{dat_name}*/\n"

          decla = find_decl dat_name
          if decla.get_ptr_level == 0 then
            file.print <<EOT
    CELLCB   *p_cellcb = GET_CELLCB(idx);
    VAR_#{dat_name} = #{dat_name};
    return E_OK;
EOT
          elsif decla.get_ptr_level == 1 then
            if( decla.get_size_is ) then
              spec = "*#{decla.get_size_is}"
            else
              spec = ""
            end
            file.print <<EOT
    CELLCB   *p_cellcb = GET_CELLCB(idx);
    memcpy( VAR_#{dat_name}, #{dat_name}, sizeof(*#{dat_name})#{spec} );
    return E_OK;
EOT
          end
        end
      else
        raise "DataPumpHolderPlugin: Unknown celentryltype #{ct_name}.#{ep_name}"
      end
    elsif ct_name == @sync_adaptor_celltype.to_sym ||
          ct_name == @async_adaptor_celltype.to_sym then
      file.print "    CELLCB  *p_cellcb = GET_CELLCB(idx);\n"
      if ! func_type.get_type.is_void? then
        file.print "    return "
      else
        file.print "  "
      end
      file.print "cOut_", func_name, "("
      delim = ""
      params.each{ |param|
        file.print "#{delim}#{param.get_name}"
        delim = ", "
      }
      file.print ");\n"
      # func_type.kind_of? (VoidType)
    else
      if ! $generate_all_template then
        # --generate-all-template オプション指定時は無視する
        raise "DataPumpHolderPlugin: Unknown celltyep #{ct_name}"
      end
    end
  end

  #===  受け口関数の preamble (C言語)を生成する
  #     必要なら preamble 部に出力する
  #      gen_cdl_file の中でで生成されたセルタイプに対して呼び出される
  #file::           FILE        出力先ファイル
  #b_singleton::    bool        true if singleton
  #ct_name::        Symbol
  #global_ct_name:: string
  def gen_preamble( file, b_singleton, ct_name, global_ct_name )
    if ct_name == @sync_adaptor_celltype.to_sym then
      file.print "    /* このセルタイプは、waitForReadDone 関数を非 oneway 化するためのもの */\n"
    elsif ct_name == @async_adaptor_celltype.to_sym then
      file.print "    /* このセルタイプは、waitForReadDone 関数を oneway 化するためのもの */\n"
    end
  end


  #== attr, var の中から探す
  # var_attr_name: Symbol: attr または var の名前
  # return: Decl : attr または var の Decl を返す
  # リニアサーチなので、効率が悪い（NameList のリストは、なかったか？）
  def find_decl var_attr_name
    @attr_list.each{ |decl| 
      if( var_attr_name == decl.get_name ) then
        return decl
      end
    }
    @var_list.each{ |decl| 
      if( var_attr_name == decl.get_name ) then
        return decl
      end
    }
    raise "DataPumpHolderPlugin: Unknown data name #{@celltype.get_name} data:#{var_attr_name}"
  end
end
